require "yaml"
require_relative "classifier/table"
require_relative "classifier/ranking"

module Portage
  module Cli
    # "What category is this?" for anything shopping-shaped: a search query,
    # a catalog product's title/description, a stores.yml/index entry, or
    # (Phase 3) a browser history/bookmark entry — one classifier, so a
    # store tagged from its product mix and a query typed by a shopper land
    # in the same category space and can be matched against each other.
    #
    # Plain keyword matching against Google's own published product taxonomy
    # (https://www.google.com/basepages/producttype/taxonomy-with-ids.en-US.txt),
    # top two levels only (~200 nodes, `known-stores/categories.yml`, shipped
    # in the gem so this works offline on a fresh brew/gem install). No LLM
    # and no network call: it has to run on every `find` and stay instant.
    # "Plain keyword" means a whole-word match (plus simple plural
    # normalization, #word_match?), not a substring regex — a substring
    # check matches in both directions ("carpet" contains "pet", "chair"
    # contains "hair", "scarf" contains "car") and was a real source of
    # false positives before this became whole-word.
    #
    # `known-stores/categories.yml` is generated by `script/categories`: a level-2
    # node's `keywords` are its own name plus its descendants', `parent_keywords`
    # are its parent's words, and `category-stoplist.yml` words are left out.
    # See Ranking for how a text is scored against it.
    module Classifier
      # `known-stores/categories.yml`, from `lib/portage/cli/classifier.rb`.
      KNOWN_PATH = File.expand_path("../../../known-stores/categories.yml", __dir__).freeze

      # Words that are never evidence of a category (`known-stores/category-stoplist.yml`,
      # `word: why`): merchandising and url words, and words that name a whole family of
      # nodes. `script/categories` leaves them out of the keywords; `categories_for`
      # drops them from its input, so the two sides agree.
      STOPLIST_PATH = File.expand_path("../../../known-stores/category-stoplist.yml", __dir__).freeze

      # The user's own additions/overrides — same id overrides a shipped
      # node's keywords, a new id extends the taxonomy. Absent by default;
      # nothing here is required for the shipped file to work.
      PATH = File.join(Dir.home, ".portage", "categories.yml").freeze

      # `/products/<slug>`, `/collections/<slug>`, `/c/<slug>`,
      # `/category/<slug>` — the URL shapes stores.yml/index/browser-import
      # entries actually carry (docs/plans/buy-skill-and-local-browser.md
      # Phase 2a/3).
      SLUG_PATTERNS = [
        %r{/products/([^/?#]+)},
        %r{/collections/([^/?#]+)},
        %r{/c/([^/?#]+)},
        %r{/category/([^/?#]+)}
      ].freeze

      # @param text [String] a query, a product title/description, or a
      #   store/product URL. Whichever it is, it's tokenized the same way
      #   (see #tokenize) so the same node keywords match all of them.
      # @param known_path [String] override for KNOWN_PATH — specs redirect
      #   this the same way SearchBackends::Allowlist takes its own `path:`.
      # @param user_path [String] override for PATH.
      # @param stoplist_path [String] override for STOPLIST_PATH.
      # @return [Array<String>] up to MAX_CATEGORIES category ids, best score
      #   first (ties: see .tie_breakers). Empty when nothing matches.
      def self.categories_for(text, known_path: KNOWN_PATH, user_path: PATH, stoplist_path: STOPLIST_PATH)
        stopped = Table.load_yaml(stoplist_path)
        counts = Ranking.word_counts(tokenize(text).reject { |word| stopped.key?(word) })
        return [] if counts.empty?

        Ranking.best(counts, Table.for(known_path, user_path), stopped)
      end

      # @return [Array<String>] the taxonomy names for `ids`, in order —
      #   `portage browser import` (Phase 3) shows a domain's guessed
      #   categories by name so the user can judge them before saving.
      def self.names_for(ids, known_path: KNOWN_PATH, user_path: PATH)
        all = Table.for(known_path, user_path).nodes
        Array(ids).filter_map { |id| all.dig(id.to_s, "name") }
      end

      # --- Tokenizing the input ---

      # A URL slug is words joined by `-`/`_` (`hand-cut-glass` — see
      # AGENTS.md's own product terminology); everything else is just
      # whitespace/punctuation-split. Both a URL's slug words and the plain
      # words of a title/description/query are kept, so "hiking boots" and
      # "https://shop.example/products/hiking-boots-mens" tokenize the same
      # way.
      # Below 3 letters, a token is noise ("a", "of", "is") rather than a
      # keyword candidate — every generated keyword is at least this long
      # too (see the script that built known-stores/categories.yml), so
      # nothing below this length could ever whole-word match one anyway.
      MIN_WORD_LENGTH = 3

      # Public rather than private — SearchBackends::Index (Phase 2b) tokenizes
      # a query and a product's title/aliases the same way this module does
      # internally, so a query and a product name land in the same word
      # space instead of re-implementing this split.
      def self.tokenize(text)
        string = text.to_s
        slug_words = SLUG_PATTERNS.filter_map { |pattern| pattern.match(string)&.[](1) }
                                  .flat_map { |slug| slug.split(/[-_]/) }
        (slug_words + string.split(/[^\p{Alpha}]+/)).map(&:downcase)
                                                    .select { |word| word.length >= MIN_WORD_LENGTH }
      end

      # Whole-word only, plus the plural forms a keyword list and a real
      # query/title actually differ by: an exact match, one plus a trailing
      # "s" or "es" ("boot"/"boots", "watch"/"watches"), or the "y"/"ies"
      # swap ("battery"/"batteries"). Deliberately not a substring check —
      # substrings match in both directions regardless of word boundaries
      # ("carpet" contains "pet", "chair" contains "hair", "scarf" contains
      # "car"), which is real noise, not stemming.
      # Public — see .tokenize's own comment; SearchBackends::Index (Phase
      # 2b) matches a query's tokens against a product's title/alias tokens
      # with this same whole-word (plus plural) rule, rather than a
      # substring check that goes both ways ("tea" in "steam"/"teak", "bag"
      # in "bagel").
      def self.word_match?(word, keyword)
        word == keyword || plural_of?(word, keyword) || plural_of?(keyword, word) || ies_y_match?(word, keyword)
      end

      # @return [Boolean] true when `plural` is `singular` plus a trailing
      # "s" or "es" ("boot"/"boots", "watch"/"watches").
      def self.plural_of?(plural, singular)
        ["#{singular}s", "#{singular}es"].include?(plural)
      end
      private_class_method :plural_of?

      # @return [Boolean] true when either side is the other's "ies" plural
      # ("battery"/"batteries").
      def self.ies_y_match?(word, keyword)
        (word.end_with?("ies") && keyword == "#{word[0..-4]}y") ||
          (keyword.end_with?("ies") && word == "#{keyword[0..-4]}y")
      end
      private_class_method :ies_y_match?
    end
  end
end
