require "spec_helper"
require "yaml"

# script/categories builds known-stores/categories.yml from Google's taxonomy
# file. It is a stdlib-only script at the repo root, so these specs load it
# and skip themselves outside the monorepo.
RSpec.describe "script/categories" do
  script = File.expand_path("../../../../script/categories", __dir__)
  fixture = File.expand_path("../../fixtures/taxonomy_tiny.txt", __dir__)

  before do
    skip "not running inside the Portage monorepo" unless File.exist?(script)
    load script unless defined?(CategoriesGenerator)
  end

  let(:taxonomy) { File.read(fixture, encoding: "UTF-8") }
  let(:stoplist) do
    { "and" => "function word", "gift" => "merchandising", "sets" => "bundle", "accessories" => "generic" }
  end

  def generate(**options) = YAML.safe_load(CategoriesGenerator.generate(taxonomy, **options))

  it "keeps the top two levels as keys, by id, in taxonomy order" do
    expect(generate.keys).to eq(%w[1 2 6 8 13 9 10])
  end

  it "keeps each node's own name as `name`, with its whole path" do
    table = generate
    expect(table["2"]["name"]).to eq("Home & Garden > Lighting")
    expect(table["1"]["name"]).to eq("Home & Garden")
  end

  it "rolls descendants' names (levels 3 and up) into a level-2 node's keywords" do
    expect(generate["2"]["keywords"]).to eq(%w[lighting fixtures chandeliers light bulbs])
  end

  it "does not roll descendants into a level-1 node" do
    expect(generate["1"]["keywords"]).to eq(%w[home garden])
  end

  it "rolls a node's descendants only into that node" do
    expect(generate["6"]["keywords"]).to eq(%w[kitchen dining appliances toasters])
    expect(generate["8"]["keywords"]).to eq(%w[lighting accessories])
  end

  it "puts the parent's words in parent_keywords, not in keywords" do
    table = generate
    expect(table["2"]["parent_keywords"]).to eq(%w[home garden])
    expect(table["2"]["keywords"]).not_to include("home")
  end

  it "leaves a parent word out of parent_keywords when the node already has it as a keyword" do
    expect(generate["13"]["keywords"]).to eq(%w[garden tools])
    expect(generate["13"]["parent_keywords"]).to eq(%w[home])
  end

  it "has no parent_keywords on a level-1 node" do
    expect(generate["1"]).not_to have_key("parent_keywords")
  end

  it "drops words under three letters and punctuation" do
    expect(generate["6"]["keywords"]).not_to include("&")
    expect(generate["2"]["keywords"]).to all(match(/\A\p{Alpha}{3,}\z/))
  end

  it "applies the stoplist to keywords and parent_keywords alike" do
    table = generate(stoplist: stoplist)
    all_words = table.values.flat_map { |node| node["keywords"] + node.fetch("parent_keywords", []) }
    expect(all_words & stoplist.keys).to eq([])
    expect(table["10"]["keywords"]).to eq(%w[clothing shirts tops])
    expect(table["9"]["keywords"]).to eq(%w[apparel])
  end

  it "merges a node's synonyms into its keywords, after the taxonomy's own" do
    synonyms = { "2" => { "pendant" => "golden case", "Sconce" => "golden case" } }
    expect(generate(synonyms: synonyms)["2"]["keywords"])
      .to eq(%w[lighting fixtures chandeliers light bulbs pendant sconce])
  end

  it "does not repeat a synonym the taxonomy already has" do
    keywords = generate(synonyms: { "2" => { "chandeliers" => "x" } })["2"]["keywords"]
    expect(keywords.count("chandeliers")).to eq(1)
  end

  it "pins the taxonomy edition in the header" do
    header = CategoriesGenerator.generate(taxonomy)
    expect(header).to start_with("# Generated by script/categories")
    expect(header).to include("edition 2099-01-01")
  end

  it "is deterministic" do
    first = CategoriesGenerator.generate(taxonomy, stoplist: stoplist)
    expect(CategoriesGenerator.generate(taxonomy, stoplist: stoplist)).to eq(first)
  end

  it "refuses a taxonomy file with no edition line" do
    expect { CategoriesGenerator.generate("1 - Home & Garden\n") }.to raise_error(/Google_Product_Taxonomy_Version/)
  end

  describe "the shipped stoplist and synonyms" do
    let(:shipped) do
      CategoriesGenerator.load_yaml(File.join(CategoriesGenerator::KNOWN_STORES, "category-stoplist.yml"))
    end

    it "gives every stoplisted word a reason" do
      expect(shipped).not_to be_empty
      expect(shipped.values).to all(be_a(String).and(satisfy { |why| why.length > 10 }))
    end

    it "lists lowercase single words" do
      expect(shipped.keys).to all(match(/\A\p{Lower}{3,}\z/))
    end

    it "drops every stoplisted word from a generated keyword list" do
      lines = shipped.keys.each_with_index.map { |word, i| "#{i + 1} - Home & Garden > #{word.capitalize} Widgets" }
      text = "# Google_Product_Taxonomy_Version: x\n#{lines.join("\n")}\n"
      table = YAML.safe_load(CategoriesGenerator.generate(text, stoplist: shipped))
      words = table.values.flat_map { |node| node["keywords"] }
      expect(words & shipped.keys).to eq([])
      expect(words).to include("widgets")
    end
  end
end
